### ISSUE TITLE
Datum zaplacení / Odeslání

### ISSUE THREAD

**Issue by janfluksa** [janfluksa/multiorder#10]
potrebuji evidovat datum zaplaceni a datum odeslani, delal to i soucasnej system (nekde se to musi zobrazovat, nemusi to byt primo viditelne)

**Comment by janfluksa** [comment]
Doplnil jsem editaci data zaplacení a odeslání v nastavení objednávky. prosím o kontrolu 

![image](https://cloud.githubusercontent.com/assets/3913922/5802966/5fc3994a-9ffa-11e4-8077-e5a535ebba9c.png)

**Comment by pufexi** [comment]
Jaj, to jsme se blbe pochopili, to nemusi byt editovatelne, spis vubec, ale klidne uz to tam nech... ale melo se to tam propisovat na zaklade zmeny stavu Platby a Dopravy tedy tech prepinacu v ojednavkach

**Comment by janfluksa** [comment]
Ty stavy jsou v databazi. Dokazu to navazat na id urciteho stavu. Nesmi ho pak ale nikdo vymazat. 

Nebo mam do tabulky tech stavu navic pridat policko s akci?

**Comment by pufexi** [comment]
Moc tomu nerozumim, stav nikdo mazat nemuze... ne? Proste asi ti nerozumim.

Ale pozadavek je velmi jednoduchy, kdyz zmenil z "neodeslano" na "odeslano" tak se napise do info: zmena stavu dopravy xx.xx.xxxx , idealne tedy i jaky je soucasny stav. To same pro platbu. Predstav si v realu to je proste k tomu, abych vedel, kdy se zbozi odeslalo a kdy zaplatilo. Coz zjistim v zalozce informace. 

Ja to drive zobrazoval prave po pridrzeni sipky na RR/BA a tak... v tom vypisu, ale tam je nyni informace co je to presne BA a zda je odeslano ci ne... takze uz by tam toho asi bylo moc, ale svym zpusobem by to tam bylo fakt uplne nejlepsi. Kdyz ten hint udelas sirsi asi by se to tam i krasne veslo

Postovni balik RR
Zasilka odeslana 
23.01.2014

By se napriklad zobrazilo.

Kdyz je zasilka neodeslana, tak dej datum nezobrazuj ci tak nejak.

**Comment by janfluksa** [comment]
Teď je to tak, že po jakékoliv změně stavu: 
1. na stav **Odesláno** se nastaví *sent = 1;* a *sent_date = Date("Y-m-d");*
2. na stav **Zaplaceno** se nastaví *paid = 1;* a *paid_date = Date("Y-m-d");*

Je to tak v pořádku?
Díky, Honza

**Comment by pufexi** [comment]
ano!
