### ISSUE TITLE
Zobrazení váhy objednávky

### ISSUE THREAD

**Issue by janfluksa** [janfluksa/multiorder#2]
vaha objednavky, pocitas s tim vubec? je to soucet vahy jednotlivych zbozi, a ta by mela byt taky upravitelna, napriklad kliknutim na cislo objednavky (v pripade treba tezsiho zabaleni)

**Comment by janfluksa** [comment]
Můžu doplnit součet váhy všech zboží v objednávce. to máme v databázi. Editovatelné to ale nebude.

Mohlo by to tam být natvrdo, ale problém bude, když přidáš nějaké další zboží. Pak by se to nepřepočítalo.

Jak to teda chceš?
Díky, H

**Comment by pufexi** [comment]
Presne tak to chci, ale prave prepocitavat jsem to chtel... chapu, ze je to asi oser, ale je logicky, ze se zbozi proste prida nekdy a pak od toho systemu ocekavam, ze to zas prepocita a ulozi si do DB objednavky pro dalsi vyuziti (export pro postu atd..) 

Nicmene nemusi to by ted editovatelne, jakoze to rucne prepisu, pokud ses ptal na toto.

**Comment by janfluksa** [comment]
OK, doplním součet vah. Když to bude potřeba změnit, je tady pořád možnost upravit to přímo ve zboží.

![image](https://cloud.githubusercontent.com/assets/3913922/5801654/df84177a-9fed-11e4-8503-cd84a8b80168.png)

**Comment by janfluksa** [comment]
Ahoj Dominiku,

celková váha objednávky je zobrazena v dialogu Položky objednávky:

![image](https://cloud.githubusercontent.com/assets/3913922/5816697/81d4855e-a0a3-11e4-8232-c3572960aa68.png)

Prosím okonotrolu.
Díky, Honza

**Comment by pufexi** [comment]
ok, closed!
