### ISSUE TITLE
Zobrazení emailu ve výpisu Objednávek

### ISSUE THREAD

**Issue by janfluksa** [janfluksa/multiorder#4]
potrebuji nekde kontaktni email na toho cloveka v objednavce, idealne ho dej za ten nick, proste Jmeno prijmeni (email, nick), ne po rozkliknuti takhle

**Comment by janfluksa** [comment]
Ahoj dominiku, email jsem doplnil. Uživatelské jméno jsem přesunul do titulku. Kvůli místa. Je to tak v pořádku? Díky, H

![image](https://cloud.githubusercontent.com/assets/3913922/5801312/ef826810-9fe9-11e4-97f5-df71df7c026a.png)

**Comment by janfluksa** [comment]
P.S. Má na tom emaillu být odkaz typu mailto?

**Comment by pufexi** [comment]
Jo, muzes to tak udelat, dobry napad.

**Comment by janfluksa** [comment]
Ok, hotovo
