### ISSUE TITLE
Seznam Firem

### ISSUE THREAD

**Issue by janfluksa** [janfluksa/multiorder#6]
Firma, potrebuji tam Dominik Škoda, Josef Škoda, Eva Hanáková, Pufexi, GourmetKava.

OK, pošli mi prosím i zkratky. Můžu je doplnit do DB.

**Comment by pufexi** [comment]
DŠ, JŠ, EH, PU, GK

**Comment by janfluksa** [comment]
Firmy jsem upravil. prosím o kontrolu. 
Trošku je problém s tím, že některé firmy se jmenují jako uživatelé systému. Tak aby se to nepletlo, navrhoval bych nějaký prefix těch firemních zkratek. 

(Třeba DŠ v poli účtoval jsi ty i tvoje firma - to by mohlo někoho splést, mohl by si myslet, že se jená o firmu DŠ)

Díky, Honza

**Comment by pufexi** [comment]
pravda, kde se vlastne zobrazuji ty prefixy? To tak do budoucna s tim pocitas?

**Comment by janfluksa** [comment]
Zatím se zkratka nikde nezobrazuje. Počítám s tím tam, kde bude málo místa.

Například toto je blbý:
![image](https://cloud.githubusercontent.com/assets/3913922/5801489/e45e0622-9feb-11e4-8725-127496bf9feb.png)

Viděl bych to na fotku uživatele a zkratku firmy + kanál
je to zbytečné vypisovat

**Comment by pufexi** [comment]
chapu, zatim asi neresme :-)

CLOSED
