### ISSUE TITLE
Doplnit platební metody

### ISSUE THREAD

**Issue by janfluksa** [janfluksa/multiorder#8]
Platebni metoda chybi PayU, BitPay a kartou, vsechny tyhle 3 nove znamenaji, ze objednavka, kterou zadavam uz je automaticky zaplacena a ready to send...

1. Dle domluvy, platební metoda nedělá v objednáve nic automaticky. Můžeme to upravit, ale domluvili jsme se, že všechny stavy se budou vybírat ručně.
2. Platební metody se upravují v databázi, už jsem je doplnil

Můžeme s tímto úkol uzavřít? Prosím o test.

**Comment by pufexi** [comment]
Chapu, otevru nove Issue, chci aby urcite platebni metody zmenili stav Platby / Dopravy

**Comment by janfluksa** [comment]
Dobře, díky za info. H
